spring:
  liquibase:
    enabled: false #if you want migrate data set true
  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
#              action: create
#              create-source: metadata
#              create-target: create.sql
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
    initialization-mode: always
    data: classpath:data.sql

server:
  port: 8080
